# Uncomment the next line to define a global platform for your project
platform :ios, '17.4'

target 'stocksApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.9.1'
  pod 'Kingfisher', '~> 7.11.0'
  # Pods for stocksApp

end
